language: python
env:
  - TOXENV=flake8
  - TOXENV=py27-django18
  - TOXENV=py33-django18
  - TOXENV=py34-django18
install:
  - pip install tox
  - pip install -r requirements.txt
script:
  - tox -e $TOXENV
